config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :sections, only: [] do
      resources :lessons, only: [:new, :create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    mount_uploader :image, ImageUploader
    
    belongs_to :user
    has_many :sections
    has_many :enrollments
   
    validates :title, presence: true
    validates :description, presence: true
    validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :section

    mount_uploader :video, VideoUploader
    
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :course
    has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        @courses = Course.all
    end
    
    def show
        @course = Course.find(params[:id])
    end    

    private

    def course_params
        params.require(:course).permit(:title, :description, :cost)
    end
       
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    before_action :authenticate_user!

  def create
    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)
end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_course, only: [:show]


    def new
        @course = Course.new
    end    

    def create
        @course = current_user.courses.create(course_params)
        if @course.valid?
            redirect_to instructor_course_path(@course)
          else
            render :new, status: :unprocessable_entity
          end
      end
    
      def show
         
      end

      private

      def require_authorized_for_current_course
        if current_course.user != current_user
          render plain: "Unauthorized", status: :unauthorized
        end
      end

      helper_method :current_course
      def current_course
        @current_course ||= Course.find(params[:id])
      end
    
      def course_params
        params.require(:course).permit(:title, :description, :cost)
      end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_section

    def new
      @lesson = Lesson.new
    end
  
    def create
      @lesson = current_section.lessons.create(lesson_params)
      redirect_to instructor_course_path(current_section.course)
    end
    
      private

      def require_authorized_for_current_section
        if current_section.course.user != current_user
          render plain: 'Unauthorized', status: :unauthorized
        end
      end
      
      helper_method :current_section
      def current_section
        @current_section ||= Section.find(params[:section_id])
      end
    
      def lesson_params
        params.require(:lesson).permit(:title, :subtitle, :video)
      end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
      before_action :authenticate_user!
      before_action :require_authorized_for_current_course

      def new
        @section = Section.new
      end

      def create
        @section = current_course.sections.create(section_params)
        redirect_to instructor_course_path(current_course)
      end
    
      private
      
      def require_authorized_for_current_course
        if current_course.user != current_user
          render plain: "Unauthorized", status: :unauthorized
        end
      end
      
      helper_method :current_course
      def current_course
        @current_course ||= Course.find(params[:course_id])
      end
    
      def section_params
        params.require(:section).permit(:title)
      end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def show
      @lesson = Lesson.show
    end
    
    private

    def require_authorized_for_current_section
      if current_section.course.user != current_user
        render plain: 'Unauthorized', status: :Unauthorized
        redirect_to course_path(current_course)
      end
     end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video)
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
      <%= image_tag course.image.to_s, :class => 'img-responsive' %>
    </h2>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <%= image_tag @course.image.to_s, class: 'img-fluid' %>
  <br />
  <div class="row">
  <div class="col-sm-4 col-12">
    <span class="badge badge-default">
     <%= number_to_currency @course.cost %>
    </span>

    <% if current_user && current_user == @course.user %>
      <br />
      <br />
      <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
    <% end %>
  
    <br />
    <br />

    <% if current_user && current_user.enrolled_in?(@course) %>
      <h3 class="badge badge-info">You Are Enrolled!</h3>
    <% else %>
      <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
    <% end %>    
  </div>

  <div class="col-sm-8 col-12">
    <%= @course.description %>
  </div>
</div>

<div class="col-12">
    <% @course.sections.each do |section| %>
      <br /><br />
      <div class="section">
        <h3>
          <%= section.title %>
        </h3> 
        <div class="row">
        <% section.lessons.each do |lesson| %>
          <div class="col-12 col-sm-6">
            <div class="lesson text-center">
            <br />              
              <%= link_to lesson_path(lesson) do %>
                <b><%= lesson.title %></b>
                <br />
                <%= lesson.subtitle %>
              <% end %>
            </div>
          </div> 
        <% end %>
      </div>
     <br class="clr" />
    </div> 
  <% end %>
 </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :image %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image.to_s, :class => 'img-responsive' %>
  <br />
  <%= link_to 'Preview As Student...', course_path(current_course), class: 'btn btn-warning float-right' %>
  <br class="clr" />

  <div class="text-center">
    <%= link_to 'Add a new section...', new_instructor_course_section_path(current_course), class: 'btn btn-primary btn-lg' %>
  </div>

  <ul>
    <% current_course.sections.each do |section| %>
      <li>
        <%= section.title %>
        <%= link_to 'New Lesson', new_instructor_section_lesson_path(section), class: 'float-right btn btn-primary btn-sm' %>
        <ul>
          <% section.lessons.each do |lesson| %>
            <li>
              <b><%= lesson.title %></b>
              -
              <%= lesson.subtitle %>
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
  
</div>

app/views/instructor/lessons/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lesson</h1>
  <%= simple_form_for @lesson, url: instructor_section_lessons_path(current_section) do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :video %>
    <br />
    <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/instructor/sections/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new section</h1>
  <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
    <%= f.input :title %>
    <br />
    <%= f.submit "Add a section", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p>
    <%= current_lesson.subtitle %>
  </p>

  <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid" controls preload="auto"  
  poster="<%= image_path('black.jpg') %>" data-setup="{}">
  <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
    <noscript>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
    </noscript>
  </video>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
    <br />
    <div class="frosty col-10 offset-1 text-center">
        <br />
        <h1>Learn Magic from the Pros</h1>
        <br />
        <h2>I'm an illusionist, Vetrual.</h2>
        <br />
        <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
        <br /><br />
    </div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a courses archive of lessons.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Join our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals.</p>
  </div>
</div>